/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Dataart-Icon-Font\'">' + entity + '</span>' + html;
	}
	var icons = {
		'da-if-actions---home': '&#xe900;',
		'da-if-actions---restore': '&#xe901;',
		'da-if-actions---net': '&#xe902;',
		'da-if-actions---settings-6-sided': '&#xe903;',
		'da-if-actions---settings-8-sided': '&#xe904;',
		'da-if-actions---like': '&#xe905;',
		'da-if-actions---like-inactive': '&#xe906;',
		'da-if-actions---bookmark': '&#xe907;',
		'da-if-actions---bookmark-inactive': '&#xe908;',
		'da-if-actions---bookmarks': '&#xe909;',
		'da-if-actions---checked': '&#xe90a;',
		'da-if-actions---checked-all': '&#xe90b;',
		'da-if-actions---delete': '&#xe90c;',
		'da-if-actions---search': '&#xe90d;',
		'da-if-actions---zoom-out': '&#xe90e;',
		'da-if-actions---zoom-in': '&#xe90f;',
		'da-if-actions---profile': '&#xe910;',
		'da-if-actions---group': '&#xe911;',
		'da-if-actions---add-friend': '&#xe912;',
		'da-if-actions---profile-login': '&#xe913;',
		'da-if-actions---calendar': '&#xe914;',
		'da-if-actions---search-page': '&#xe915;',
		'da-if-actions---search-doc': '&#xe916;',
		'da-if-actions---filter': '&#xe917;',
		'da-if-actions---lock': '&#xe918;',
		'da-if-actions---unlock': '&#xe919;',
		'da-if-actions---plus': '&#xe91a;',
		'da-if-actions---minus': '&#xe91b;',
		'da-if-actions---plus-filled': '&#xe91c;',
		'da-if-actions---minus-filled': '&#xe91d;',
		'da-if-actions---plus-outline': '&#xe91e;',
		'da-if-actions---minus-outline': '&#xe91f;',
		'da-if-actions---plus-box': '&#xe920;',
		'da-if-actions---minus-box': '&#xe921;',
		'da-if-actions---plus-box-outline': '&#xe922;',
		'da-if-actions---minus-box-outline': '&#xe923;',
		'da-if-audio---play': '&#xe924;',
		'da-if-audio---pause': '&#xe925;',
		'da-if-audio---stop': '&#xe926;',
		'da-if-audio---previous': '&#xe927;',
		'da-if-audio---next': '&#xe928;',
		'da-if-audio---rewind': '&#xe929;',
		'da-if-audio---forward': '&#xe92a;',
		'da-if-audio---volume-mute': '&#xe92b;',
		'da-if-audio---volume-down': '&#xe92c;',
		'da-if-audio---volume-up': '&#xe92d;',
		'da-if-audio---volume-off': '&#xe92e;',
		'da-if-audio---mic': '&#xe92f;',
		'da-if-audio---mic_off': '&#xe930;',
		'da-if-communication---call': '&#xe931;',
		'da-if-communication---chat': '&#xe932;',
		'da-if-devices---monitor-desktop': '&#xe933;',
		'da-if-devices---iphone': '&#xe934;',
		'da-if-devices---ipad-tablet': '&#xe935;',
		'da-if-devices---imac': '&#xe936;',
		'da-if-devices---apple-watch': '&#xe937;',
		'da-if-devices---macbook-laptop': '&#xe938;',
		'da-if-devices---ipod': '&#xe939;',
		'da-if-devices---headphones': '&#xe93a;',
		'da-if-devices---headset': '&#xe93b;',
		'da-if-devices---joystick-games': '&#xe93c;',
		'da-if-devices---photo-camera': '&#xe93d;',
		'da-if-devices---server': '&#xe93e;',
		'da-if-devices---mouse': '&#xe93f;',
		'da-if-devices---floppy-save': '&#xe940;',
		'da-if-editor---redo': '&#xe941;',
		'da-if-editor---undo': '&#xe942;',
		'da-if-editor---attach-hyperlink': '&#xe943;',
		'da-if-editor---image': '&#xe944;',
		'da-if-editor---file': '&#xe945;',
		'da-if-editor---eraser': '&#xe946;',
		'da-if-editor---eraser-filled': '&#xe947;',
		'da-if-file---folder': '&#xe948;',
		'da-if-file---folder-border': '&#xe949;',
		'da-if-file---folders': '&#xe94a;',
		'da-if-file---add-folder': '&#xe94b;',
		'da-if-file---delete-folder': '&#xe94c;',
		'da-if-file---shared-folder': '&#xe94d;',
		'da-if-file---move-folder': '&#xe94e;',
		'da-if-file---upload-folder': '&#xe94f;',
		'da-if-file---download-folder': '&#xe950;',
		'da-if-file---image-folder': '&#xe951;',
		'da-if-file---file-document': '&#xe952;',
		'da-if-file---list-poll': '&#xe953;',
		'da-if-file---word-file': '&#xe954;',
		'da-if-file---excel-file': '&#xe955;',
		'da-if-file---powerpoint-file': '&#xe956;',
		'da-if-file---database': '&#xe957;',
		'da-if-file---multiple-files-sheets': '&#xe958;',
		'da-if-file---document-file-sheet': '&#xe959;',
		'da-if-file---attachment': '&#xe95a;',
		'da-if-file---upload': '&#xe95b;',
		'da-if-file---download': '&#xe95c;',
		'da-if-file---cloud': '&#xe95d;',
		'da-if-file---cloud-border': '&#xe95e;',
		'da-if-file---cloud-upload': '&#xe95f;',
		'da-if-file---cloud-download': '&#xe960;',
		'da-if-file---cloud-check': '&#xe961;',
		'da-if-editor---image-multiple': '&#xe962;',
		'da-if-editor---rotate-left': '&#xe963;',
		'da-if-editor---rotate-right': '&#xe964;',
		'da-if-editor---edit': '&#xe965;',
		'da-if-logo---facebook': '&#xe966;',
		'da-if-logo---twitter': '&#xe967;',
		'da-if-logo---vkontakte': '&#xe968;',
		'da-if-logo---youtube': '&#xe969;',
		'da-if-navigation---menu-apps': '&#xe96a;',
		'da-if-navigation---menu-hamburger': '&#xe96b;',
		'da-if-navigation---arrow-left': '&#xe96c;',
		'da-if-navigation---arrow-down': '&#xe96d;',
		'da-if-navigation---arrow-right': '&#xe96e;',
		'da-if-navigation---arrow-up': '&#xe96f;',
		'da-if-navigation---check': '&#xe970;',
		'da-if-navigation---chevron-left': '&#xe971;',
		'da-if-navigation---chevron-right': '&#xe972;',
		'da-if-navigation---chevron-up': '&#xe973;',
		'da-if-navigation---chevron-down': '&#xe974;',
		'da-if-navigation---close': '&#xe975;',
		'da-if-navigation---all-back': '&#xe976;',
		'da-if-navigation---fullscreen': '&#xe977;',
		'da-if-navigation---exit-fullscreen': '&#xe978;',
		'da-if-navigation---all-forward': '&#xe979;',
		'da-if-navigation---refresh': '&#xe97a;',
		'da-if-navigation---arrow-level-down-right': '&#xe97b;',
		'da-if-navigation---arrow-level-down-left': '&#xe97c;',
		'da-if-navigation---chevrons-unfold-less': '&#xe97d;',
		'da-if-navigation---chevrons-unfold-more': '&#xe97e;',
		'da-if-navigation---more-horizontal': '&#xe97f;',
		'da-if-navigation---more-vertical': '&#xe980;',
		'da-if-navigation---dropdown-triangle-down': '&#xe981;',
		'da-if-navigation---dropdown-triangle-up': '&#xe982;',
		'da-if-navigation---triangle-left': '&#xe983;',
		'da-if-navigation---triangle-right': '&#xe984;',
		'da-if-navigation---triangle-filled-down': '&#xe985;',
		'da-if-navigation---triangle-filled-up': '&#xe986;',
		'da-if-navigation---triangle-filled-right': '&#xe987;',
		'da-if-navigation---triangle-filled-left': '&#xe988;',
		'da-if-navigation---filled-close': '&#xe989;',
		'da-if-toggle---checkbox-checked': '&#xe98a;',
		'da-if-toggle---checkbox-unchecked': '&#xe98b;',
		'da-if-toggle---check-box-indeterminate': '&#xe98c;',
		'da-if-toggle---radiobutton-on': '&#xe98d;',
		'da-if-toggle---radiobutton-off': '&#xe98e;',
		'da-if-toggle---star': '&#xe98f;',
		'da-if-toggle---star-border': '&#xe990;',
		'da-if-toggle---star-half': '&#xe991;',
		'da-if-misc---cart': '&#xe992;',
		'da-if-misc---cart-border': '&#xe993;',
		'da-if-misc---bell-notification': '&#xe994;',
		'da-if-misc---pin': '&#xe995;',
		'da-if-gambling---suit-spades': '&#xe996;',
		'da-if-gambling---crown': '&#xe997;',
		'da-if-gambling---suit-hearts': '&#xe998;',
		'da-if-gambling---suit-diamonds': '&#xe999;',
		'da-if-gambling---suit-clubs': '&#xe99a;',
		'da-if-gambling---suit-dice': '&#xe99b;',
		'da-if-finance---bank': '&#xe99c;',
		'da-if-finance---curency-sign': '&#xe99d;',
		'da-if-finance---curency-usd': '&#xe99e;',
		'da-if-finance---curency-usd-no': '&#xe99f;',
		'da-if-finance---curency-euro': '&#xe9a0;',
		'da-if-finance---curency-gbr': '&#xe9a1;',
		'da-if-finance---curency-jpy': '&#xe9a2;',
		'da-if-finance---curency-rub': '&#xe9a3;',
		'da-if-finance---curency-ind': '&#xe9a4;',
		'da-if-finance---curency-krw': '&#xe9a5;',
		'da-if-finance---curency-thb': '&#xe9a6;',
		'da-if-finance---curency-btc': '&#xe9a7;',
		'da-if-finance---curency-eth': '&#xe9a8;',
		'da-if-finance---curency-eth2': '&#xe9a9;',
		'da-if-finance---curency-xrp': '&#xe9aa;',
		'da-if-finance---curency-eos': '&#xe9ab;',
		'da-if-finance---curency-btc-round-filled': '&#xe9ac;',
		'da-if-finance---curency-eth-round-filled': '&#xe9ad;',
		'da-if-finance---curency-eth-logo-round-filled': '&#xe9ae;',
		'da-if-finance---curency-xrp-round-filled': '&#xe9af;',
		'da-if-finance---curency-eos-round-filled': '&#xe9b0;',
		'da-if-finance---chart-areaspline': '&#xe9b1;',
		'da-if-finance---chart-arc': '&#xe9b2;',
		'da-if-finance---chart-bar': '&#xe9b3;',
		'da-if-finance---chartbar-stacked': '&#xe9b4;',
		'da-if-finance---chart-pie': '&#xe9b5;',
		'da-if-finance---credit-card': '&#xe9b6;',
		'da-if-finance---credit-card-no': '&#xe9b7;',
		'da-if-finance---credit-card-plus': '&#xe9b8;',
		'da-if-finance---credit-card-check': '&#xe9b9;',
		'da-if-finance---credit-card-cancel': '&#xe9ba;',
		'da-if-finance---credit-card-multiple': '&#xe9bb;',
		'da-if-finance---credit-card-scan': '&#xe9bc;',
		'da-if-finance---credit-card-settings': '&#xe9bd;',
		'da-if-health-care---heartbeat': '&#xe9be;',
		'da-if-health-care---heartbeat-border': '&#xe9bf;',
		'da-if-health-care---pill': '&#xe9c0;',
		'da-if-health-care---laboratory': '&#xe9c1;',
		'da-if-sport---sport-climbing': '&#xe9c2;',
		'da-if-sport---sport-cricket': '&#xe9c3;',
		'da-if-sport---sport-cycling': '&#xe9c4;',
		'da-if-sport---sport-jogging': '&#xe9c5;',
		'da-if-sport---sport-running': '&#xe9c6;',
		'da-if-sport---sport-football': '&#xe9c7;',
		'da-if-sport---sport-hiking': '&#xe9c8;',
		'da-if-sport---sport-yoga': '&#xe9c9;',
		'da-if-sport---sport-volleyball': '&#xe9ca;',
		'da-if-sport---sport-karting': '&#xe9cb;',
		'da-if-sport---sport-chess': '&#xe9cc;',
		'da-if-sport---sport-table-games': '&#xe9cd;',
		'da-if-sport---sport-bowling': '&#xe9ce;',
		'da-if-sport---sport-ping-pong': '&#xe9cf;',
		'da-if-sport---sport-aerobics': '&#xe9d0;',
		'da-if-sport---sport-badminton': '&#xe9d1;',
		'da-if-sport---sport-baseball': '&#xe9d2;',
		'da-if-sport---sport-basketball': '&#xe9d3;',
		'da-if-sport---sport-boxing': '&#xe9d4;',
		'da-if-sport---sport-canicross': '&#xe9d5;',
		'da-if-transport---car-side': '&#xe9d6;',
		'da-if-transport---truck-side': '&#xe9d7;',
		'da-if-transport---parking-sign': '&#xe9d8;',
		'da-if-transport---parking-sign-stroke': '&#xe9d9;',
		'da-if-transport---parking-payment': '&#xe9da;',
		'da-if-transport---plane-up': '&#xe9db;',
		'da-if-transport---plane-down': '&#xe9dc;',
		'da-if-transport---plane-straight': '&#xe9dd;',
		'da-if-transport---plane-face': '&#xe9de;',
		'da-if-transport---plane': '&#xe9df;',
		'da-if-transport---car-face': '&#xe9e0;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/da-if-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
